# Generated by Django 4.0.6 on 2022-10-29 07:37

from django.db import migrations, models
import firstapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdetails',
            name='images',
            field=models.ImageField(null=True, upload_to=firstapp.models.upload_to),
        ),
    ]
